name: metrics
on:
  schedule: [{cron: "0 0-23/8 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Zurich
          base: header, activity, community
          plugin_languages: yes
          plugin_languages_ignored: Makefile
          plugin_languages_details: bytes-size, percentage
          plugin_notable: yes
          plugin_followup: yes
          plugin_followup_archived: no
          plugin_topics: yes
          plugin_topics_mode: labels
          plugin_topics_sort: activity
          plugin_activity: yes
          plugin_activity_limit: 3
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          filename: metrics.svg
          config_display: large
